### ISSUE TITLE
Hang on world save phase with the fusion crafter placed in world?

### ISSUE THREAD

**Issue by coaber** [TheLMiffy1111/PackagedDraconic#1]
I've been having this strange issue with my world getting stuck at the world save phase each time after quitting, which forced me to close the game from task manager. I've asked around and people said it may of been FTB Backups causing it. Yesterday all of a sudden the world started to save as normal after a few seconds, and let me return to main screen, but it turns out the fusion crafter and the packagers connected to the ME were straight up removed from the world. Could this be related? 
PackagedDraconic 3.0.0.0
PackagedAuto 3.1.2.20
AE2 11.7.0
FML 40.2.0
(debug uploaded as compressed as it's around 40 megs in size, weirdly enough)
[debug-2.log.gz](https://github.com/TheLMiffy1111/PackagedDraconic/files/11021807/debug-2.log.gz)
I can provide further information if requested.

**Comment by coaber** [comment]
Coming with an update, i went on a test world and tested the exact same setup, hooked to a ME and requesting random craft through the fusion crafter, attempting to quit to menu will make the client hang and sit at the saving world phase. Breaking the fusion crafter and the packagers assembly will let me quit to main menu without a hang. 
video of bug reproduction: check description for time stamp https://youtu.be/NZyDXSH5JQs
debug log of latest instance
[debug-2.log.gz](https://github.com/TheLMiffy1111/PackagedDraconic/files/11023014/debug-2.log.gz)

**Comment by TheLMiffy1111** [comment]
Should be fixed
