### ISSUE TITLE
Ticking Block Entity Crash on Marked Injector Placement

### ISSUE THREAD

**Issue by Jacobsf-AS** [TheLMiffy1111/PackagedDraconic#2]
Upon placing any marked injector on a dedicated server, the server will instantly crash with the crash report attached below. 
[crash-2024-03-02_23.37.48-server.txt](https://github.com/TheLMiffy1111/PackagedDraconic/files/14471892/crash-2024-03-02_23.37.48-server.txt)

**Comment by Jacobsf-AS** [comment]
Further testing has revealed that the crashing occurs on the 1.12.2-1.0.0.10 in particular. Older versions do not cause the crash.

**Comment by TheLMiffy1111** [comment]
Please check if 1.12.2-1.0.0.11 fixes this issue

**Comment by Jacobsf-AS** [comment]
Version 1.12.2-1.0.0.11 appears to have fixed the issue and the mod is now working as expected.
