### ISSUE TITLE
Server crashes when fusion crafting

### ISSUE THREAD

**Issue by Serionard** [TheLMiffy1111/PackagedDraconic#3]
I was trying to auto-craft awakened core on DE for 1.12.2 and server crashed while ejecting core. I am using AE2: UEL Extended and catserver core.
[crash-2024-04-28_16.47.21-server.txt](https://github.com/TheLMiffy1111/PackagedDraconic/files/15142695/crash-2024-04-28_16.47.21-server.txt)

UPD:
Tried the same setup on earlier version (1.0.0.11 instead of 1.0.0.12) and crash did not happen

**Comment by TheLMiffy1111** [comment]
Should be fixed in 1.0.0.13

**Comment by Serionard** [comment]
Yep, now it works. Thanks!
