### ISSUE TITLE
Expand the number of coding slots for PackagedDraconic

### ISSUE THREAD

**Issue by sddsd2332** [TheLMiffy1111/PackagedDraconic#4]
HI
I have a recipe implemented on Fusion Crafting in DR
[He needs a total of 53 slots](https://github.com/sddsd2332/Mekanism-CE-Unofficial-1.12.2/blob/RFG/src/main/java/mekanism/common/MekanismRecipe.java#L498-L509)
But PackagedDraconic only has 48 slots
Is it possible to replace PackagedDraconic to a maximum of 54 slots?

**Comment by TheLMiffy1111** [comment]
done
