### ISSUE TITLE
1.20.1 Thinks it is missing tools for crafting.

### ISSUE THREAD

**Issue by jusitnboggs** [TheLMiffy1111/PackagedDraconic#5]
Thinks it is missing tools for crafting.  The system knows how to craft everything and has multiple crafting cpus and fusion setup even has some of the tools already in the storage.

Crafts other items in the fusion crafter as expected. 

I have tried different settings on the packager and unpackager. 

Happens in 1.18.2 and 1.20.1

![Screenshot 2024-11-07 030554](https://github.com/user-attachments/assets/f5963e26-a5ff-419c-9a2c-f8b3b0fb03f4)
![Screenshot 2024-11-07 030416](https://github.com/user-attachments/assets/62da01a2-6e26-4c06-9121-25d95f557237)
![Screenshot 2024-11-07 030347](https://github.com/user-attachments/assets/e556e353-9ee1-4bbb-8a27-c1740bee5bdc)

**Comment by TheLMiffy1111** [comment]
PackagedAuto currently requires exact nbt match
